export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>NextMile</title>
        <meta name="description" content="Get access to the best e-learning" />
      </head>
      <body className="bg-white antialiased">{children}</body>
    </html>
  );
}
